version: "3.8"

services:
  cms:
    build:
      context: ../cms
      dockerfile: ../dev-config/Dockerfile.cms
    ports:
      - "1337:1337"
    restart: always
    volumes:
      - .:/cms
    env_file:
      - .env
  frontend:
    build:
      context: ../nonna.ru
      dockerfile: ../dev-config/Dockerfile.frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/frontend
  nginx:
    container_name: nonna-nginx
    build: ../nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - cms
    # volumes:
    #   - static:/www/data/static
    #   - media:/www/data/media
    #   - ./dockerfiles/nginx/www.evacode.org.crt:/etc/ssl/private/www.evacode.org.crt
    #   - ./dockerfiles/nginx/www.evacode.org.key:/etc/ssl/private/www.evacode.org.key
