FROM oven/bun:1.1.3-alpine AS build

WORKDIR /opt/app

COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

FROM node:18.20.2-alpine AS runtime

ENV NODE_ENV=production \
    HOST=0.0.0.0 \
    PORT=3000

RUN apk add --no-cache su-exec

WORKDIR /opt/app

COPY --from=build --chown=node:node /opt/app/.output ./.output
COPY --chown=root:root --chmod=755 docker-entrypoint.sh /usr/local/bin/frontend-entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["frontend-entrypoint.sh"]
CMD ["node", ".output/server/index.mjs"]
