FROM node:18.20.2-alpine AS build

RUN apk add --no-cache build-base python3 vips-dev git

ENV NODE_ENV=production
WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm config set fetch-retry-maxtimeout 600000 -g \
    && npm ci --omit=dev

COPY . .
ARG STRAPI_PUBLIC_URL
ENV STRAPI_PUBLIC_URL=$STRAPI_PUBLIC_URL
RUN npm run build

FROM node:18.20.2-alpine AS runtime

RUN apk add --no-cache su-exec vips vips-cpp

ENV NODE_ENV=production
WORKDIR /opt/app

COPY --from=build --chown=node:node /opt/app ./
COPY --chown=root:root --chmod=755 docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN mkdir -p /opt/app/.tmp /opt/app/public/uploads /opt/app/seed \
    && chown node:node /opt/app/.tmp /opt/app/public/uploads

EXPOSE 1337

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["npm", "run", "start"]
